name: starter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  intl_translation: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/icons/app/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app/android/launcher_icon.png"
  adaptive_icon_background: "assets/icons/app/android/res/mipmap-hdpi/mokkal_launcher_background.png"
  adaptive_icon_foreground: "assets/icons/app/android/res/mipmap-hdpi/mokkal_launcher_foreground.png"

flutter_native_splash:
  color: "#6A3DE8"
  color_dark: "#331488"
  image: assets/images/logo.dark.png
  background_image_dark: assets/images/splash.png
  image_dark: assets/images/logo.dark.png

  android_12:
    color: "#6A3DE8"
    color_dark: "#331488"
    image: assets/images/logo.dark.png
    background_image_dark: assets/images/splash.png
    image_dark: assets/images/logo.dark.png

  web: false